title: Foodie Bloggy
description: Looking at the variations of type used within fast food restaurants.
footer_text: Copyright 2021 Eve Reekie
header_feature_image: ../uploads/burger-g1bfe22d59_1920.jpg
header_text: Foodie Fonts
header_text_color: "#f7f5f7"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/blog-logo.png
favicon: ../uploads/favicon.png
gridlayout: true
fixednavbar: true
upzoom: true
items: []
