title: Typoggers
description: Looking at the variations of type used within fast food chains.
footer_text: Copyright 2021 Eve Reekie
header_feature_image: ../uploads/tortilla.heic
header_text: Typography In Fast Food
header_text_color: "#0c0b0c"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: true
fixednavbar: true
upzoom: true
items: []
