title: Typoggy
description: A website with a blog
footer_text: Copyright 2021 Eve Reekie
header_feature_image: ../uploads/iridescence.heic
header_text: Typoggy Website
header_text_color: "#ffffff"
bannerheight: 100vh
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
